### ISSUE TITLE
development

### ISSUE THREAD

**Issue by javadmsd** [sadafamininia99/Speed_game#2]
این بازی رو از کجا پیدا کردی؟ خیلی باحاله، تا امتیاز ۱۴ رفتم جلو :)
دو تا کار قشنگ میشه روش انجام داد، یکی اینکه از یه وب سرویس یه لیست بلند از کلمات رو بگیریم که تکراری بودنش هم کمتر بشه
و اینکه واسه قسمت امتیاز هاش به یه وب سرویس آنلاین وصلش کنیم و هر کسی بازی کرد بالاترین امتیازش اونجا ثبت بشه

**Comment by javadmsd** [comment]
https://random-word-api.herokuapp.com/word?number=1000

**Comment by sadafamininia99** [comment]
براد تراورسی زده بود اینو :/
خیلی خفن میشهههههه
